Revert "[compiler][js] Add Support for Private Properties"
This reverts commit cbaa148e4efdbcd0dde37d175f97111a7dc112ec.

Reason for revert: 
Increased Fuzzilli crashiness:
Fuzzilli/JsOperations.swift:121: Fatal error: All guardable operations should be handled

Original change's description:
> [compiler][js] Add Support for Private Properties
>
> We are adding support so the following JS:
>
> ```
>     class A {
>       #p = 42;
>       get #val() { return this.#p; }
>       set #val(v) { this.#p = v; }
>
>       #m() { return this.#val; }
>
>       test() {
>         this.#val = 100;
>         return this.#m();
>       }
>     }
> ```
>
> can be compiled with `swift run FuzzILTool --compile` and lifted back to
> JS with `swift run FuzzILTool --lift[Corpus]ToJS`. This should allow
> over a thousand more test262 to be be loaded as seeds and to pass the
> `transpile_tests.py` chain.
>
> Bug: 534650967
> Change-Id: I9bed5e50f6975027c3afe06cdef6dbe5405d4264
> Reviewed-on: https://chrome-internal-review.googlesource.com/c/v8/fuzzilli/+/9542977
> Commit-Queue: Raphaël Hérouart <rherouart@google.com>
> Reviewed-by: Michael Achenbach <machenbach@google.com>

Bug: 534650967
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: I92f07b9e8165c1a696b14052e98a6af9b5bd3e2b
Reviewed-on: https://chrome-internal-review.googlesource.com/c/v8/fuzzilli/+/9573635
Auto-Submit: Michael Achenbach <machenbach@google.com>
Commit-Queue: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>