(Modified/Patched) Reland of "[compiler][js] Add Support for Private Properties"
This reverts commit 8ed2644935ddc425837881792b56128778a5c6e2.

Reason for revert: Reland with correction


To statically prevent the bug from happening again (at compile time):

    - `GuardableOperation` is now a protocol requiring `isGuarded: Bool`
      and a `withGuardedState(_:) -> GuardableOperation` mapping function.
    - All 19 guardable subclasses now explicitly declare their own storage
      for `isGuarded` and provide a concrete implementation returning a
      toggled copy of themselves.
    - The fragile static `switch` evaluation has been deleted entirely
      in favor of polymorphic dispatch (`op.withGuardedState(true)`).



Original change's description:
> Revert "[compiler][js] Add Support for Private Properties"
>
> This reverts commit cbaa148e4efdbcd0dde37d175f97111a7dc112ec.
>
> Reason for revert:
> Increased Fuzzilli crashiness:
> Fuzzilli/JsOperations.swift:121: Fatal error: All guardable operations should be handled
>
> Original change's description:
> > [compiler][js] Add Support for Private Properties
> >
> > We are adding support so the following JS:
> >
> > ```
> >     class A {
> >       #p = 42;
> >       get #val() { return this.#p; }
> >       set #val(v) { this.#p = v; }
> >
> >       #m() { return this.#val; }
> >
> >       test() {
> >         this.#val = 100;
> >         return this.#m();
> >       }
> >     }
> > ```
> >
> > can be compiled with `swift run FuzzILTool --compile` and lifted back to
> > JS with `swift run FuzzILTool --lift[Corpus]ToJS`. This should allow
> > over a thousand more test262 to be be loaded as seeds and to pass the
> > `transpile_tests.py` chain.
> >
> > Bug: 534650967
> > Change-Id: I9bed5e50f6975027c3afe06cdef6dbe5405d4264
> > Reviewed-on: https://chrome-internal-review.googlesource.com/c/v8/fuzzilli/+/9542977
> > Commit-Queue: Raphaël Hérouart <rherouart@google.com>
> > Reviewed-by: Michael Achenbach <machenbach@google.com>
>
> Bug: 534650967
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Change-Id: I92f07b9e8165c1a696b14052e98a6af9b5bd3e2b
> Reviewed-on: https://chrome-internal-review.googlesource.com/c/v8/fuzzilli/+/9573635
> Auto-Submit: Michael Achenbach <machenbach@google.com>
> Commit-Queue: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>
> Bot-Commit: rubber-stamper@appspot.gserviceaccount.com <rubber-stamper@appspot.gserviceaccount.com>

Bug: 534650967
Change-Id: I7626b7478d7cd302ba730957bcc0a0dac142d7ec
Reviewed-on: https://chrome-internal-review.googlesource.com/c/v8/fuzzilli/+/9573636
Reviewed-by: Michael Achenbach <machenbach@google.com>
Commit-Queue: Raphaël Hérouart <rherouart@google.com>